apiVersion: apps/v1
kind: Deployment
metadata:
  name: level3
  labels:
    app: level3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: level3
  template:
    metadata:
      labels:
        app: level3
    spec:
      containers:
        - image: gcr.io/engaged-proxy-170419/forwarder@sha256:a6c3aad06b69f9b5fe4121557f91a5d0adae48d8a306386b1cd0da9afaf11b0b
          name: level3
          ports:
            - containerPort: 9090
              name: http
          env:
            - name: MESSAGE
              value: "level3"
            - name: SLOWDOWN_CHANCE
              value: "0.1"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: level3
spec:
  selector:
    app: level3
  ports:
  - name: http
    port: 80
    targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: level2
  labels:
    app: level2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: level2
  template:
    metadata:
      labels:
        app: level2
    spec:
      containers:
        - image: gcr.io/engaged-proxy-170419/forwarder@sha256:a6c3aad06b69f9b5fe4121557f91a5d0adae48d8a306386b1cd0da9afaf11b0b
          name: level2
          ports:
            - containerPort: 9091
              name: http
          env:
            - name: MESSAGE
              value: "level2"
            - name: NEXT_URL
              value: "http://level3"
            - name: BIND
              value: ":9091"
            - name: FORWARD_CHANCE
              value: "0.5"
            - name: SLOWDOWN_CHANCE
              value: "0.1"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: level2
spec:
  selector:
    app: level2
  ports:
  - name: http
    port: 80
    targetPort: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: level1
  labels:
    app: level1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: level1
  template:
    metadata:
      labels:
        app: level1
    spec:
      containers:
        - image: gcr.io/engaged-proxy-170419/forwarder@sha256:a6c3aad06b69f9b5fe4121557f91a5d0adae48d8a306386b1cd0da9afaf11b0b
          name: level1
          ports:
            - containerPort: 9092
              name: http
          env:
            - name: MESSAGE
              value: "level1"
            - name: NEXT_URL
              value: "http://level2"
            - name: BIND
              value: ":9092"
            - name: FORWARD_CHANCE
              value: "0.9"
            - name: ERROR_CHANCE
              value: "0.05"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: level1
spec:
  selector:
    app: level1
  ports:
  - name: http
    port: 80
    targetPort: 9092
